=== ahorjia/congress_resume/schema/session_1.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "url": {
      "type": "string"
    },
    "created_date": {
      "type": "string"
    },
    "congress": {
      "type": "integer"
    },
    "session": {
      "type": "integer"
    },
    "report_date": {
      "type": "string"
    },
    "legislative_activity": {
      "type": "object",
      "properties": {
        "start_date": {
          "type": "string"
        },
        "end_date": {
          "type": "string"
        },
        "senate": {
          "type": "object",
          "properties": {
            "days_in_session": {
              "type": "integer"
            },
            "time_in_session": {
              "type": "string"
            },
            "congressional_record": {
              "type": "object",
              "properties": {
                "pages_of_proceedings": {
                  "type": "integer"
                }
              },
              "required": [
                "pages_of_proceedings"
              ]
            },
            "public_bills_enacted_into_law": {
              "type": "integer"
            },
            "measures_passed_total": {
              "type": "object",
              "properties": {
                "total": {
                  "type": "integer"
                },
                "senate_bills": {
                  "type": "integer"
                },
                "house_bills": {
                  "type": "integer"
                },
                "senate_joint_resolutions": {
                  "type": "integer"
                },
                "house_joint_resolutions": {
                  "type": "integer"
                },
                "senate_concurrent_resolutions": {
                  "type": "integer"
                },
                "house_concurrent_resolutions": {
                  "type": "integer"
                },
                "simple_resolutions": {
                  "type": "integer"
                }
              },
              "required": [
                "total",
                "senate_bills",
                "house_bills",
                "senate_joint_resolutions",
                "house_joint_resolutions",
                "senate_concurrent_resolutions",
                "house_concurrent_resolutions",
                "simple_resolutions"
              ]
            },
            "measures_reported_total": {
              "type": "object",
              "properties": {
                "total": {
                  "type": "integer"
                },
                "senate_bills": {
                  "type": "integer"
                },
                "house_bills": {
                  "type": "integer"
                },
                "senate_joint_resolutions": {
                  "type": "integer"
                },
                "simple_resolutions": {
                  "type": "integer"
                }
              },
              "required": [
                "total",
                "senate_bills",
                "house_bills",
                "senate_joint_resolutions",
                "simple_resolutions"
              ]
            },
            "special_reports": {
              "type": "integer"
            },
            "measures_pending_on_calendar": {
              "type": "integer",
              "optional": true
            },
            "measures_introduced_total": {
              "type": "object",
              "properties": {
                "total": {
                  "type": "integer"
                },
                "bills": {
                  "type": "integer"
                },
                "joint_resolutions": {
                  "type": "integer"
                },
                "concurrent_resolutions": {
                  "type": "integer"
                },
                "simple_resolutions": {
                  "type": "integer"
                }
              },
              "required": [
                "total",
                "bills",
                "joint_resolutions",
                "concurrent_resolutions",
                "simple_resolutions"
              ]
            },
            "quorum_calls": {
              "type": "integer"
            },
            "yea_and_nay_votes": {
              "type": "integer"
            }
          },
          "required": [
            "days_in_session",
            "time_in_session",
            "congressional_record",
            "public_bills_enacted_into_law",
            "measures_passed_total",
            "measures_reported_total",
            "special_reports",
            "measures_introduced_total",
            "quorum_calls",
            "yea_and_nay_votes"
          ]
        },
        "house": {
          "type": "object",
          "properties": {
            "days_in_session": {
              "type": "integer"
            },
            "time_in_session": {
              "type": "string"
            },
            "congressional_record": {
              "type": "object",
              "properties": {
                "pages_of_proceedings": {
                  "type": "integer"
                },
                "extensions_of_remarks": {
                  "type": "integer",
                  "optional": true
                }
              },
              "required": [
                "pages_of_proceedings"
              ]
            },
            "public_bills_enacted_into_law": {
              "type": "integer"
            },
            "measures_passed_total": {
              "type": "object",
              "properties": {
                "total": {
                  "type": "integer"
                },
                "senate_bills": {
                  "type": "integer"
                },
                "house_bills": {
                  "type": "integer"
                },
                "senate_joint_resolutions": {
                  "type": "integer"
                },
                "house_joint_resolutions": {
                  "type": "integer"
                },
                "senate_concurrent_resolutions": {
                  "type": "integer"
                },
                "house_concurrent_resolutions": {
                  "type": "integer"
                },
                "simple_resolutions": {
                  "type": "integer"
                }
              },
              "required": [
                "total",
                "senate_bills",
                "house_bills",
                "senate_joint_resolutions",
                "house_joint_resolutions",
                "senate_concurrent_resolutions",
                "house_concurrent_resolutions",
                "simple_resolutions"
              ]
            },
            "measures_reported_total": {
              "type": "object",
              "properties": {
                "total": {
                  "type": "integer"
                },
                "house_bills": {
                  "type": "integer"
                },
                "house_joint_resolutions": {
                  "type": "integer"
                },
                "simple_resolutions": {
                  "type": "integer"
                }
              },
              "required": [
                "total",
                "house_bills",
                "house_joint_resolutions",
                "simple_resolutions"
              ]
            },
            "special_reports": {
              "type": "integer"
            },
            "measures_pending_on_calendar": {
              "type": "integer",
              "optional": true
            },
            "measures_introduced_total": {
              "type": "object",
              "properties": {
                "total": {
                  "type": "integer"
                },
                "bills": {
                  "type": "integer"
                },
                "joint_resolutions": {
                  "type": "integer"
                },
                "concurrent_resolutions": {
                  "type": "integer"
                },
                "simple_resolutions": {
                  "type": "integer"
                }
              },
              "required": [
                "total",
                "bills",
                "joint_resolutions",
                "concurrent_resolutions",
                "simple_resolutions"
              ]
            },
            "quorum_calls": {
              "type": "integer"
            },
            "yea_and_nay_votes": {
              "type": "integer"
            }
          },
          "required": [
            "days_in_session",
            "time_in_session",
            "congressional_record",
            "public_bills_enacted_into_law",
            "measures_passed_total",
            "measures_reported_total",
            "special_reports",
            "measures_introduced_total",
            "quorum_calls",
            "yea_and_nay_votes"
          ]
        },
        "total": {
          "type": "object",
          "properties": {
            "measures_passed_total": {
              "type": "object",
              "properties": {
                "total": {
                  "type": "integer",
                  "optional": true
                }
              }
            },
            "measures_reported_total": {
              "type": "object",
              "properties": {
                "total": {
                  "type": "integer",
                  "optional": true
                }
              }
            },
            "measures_introduced_total": {
              "type": "object",
              "properties": {
                "total": {
                  "type": "integer",
                  "optional": true
                }
              }
            }
          },
          "required": [
            "measures_passed_total",
            "measures_reported_total",
            "measures_introduced_total"
          ]
        }
      },
      "required": [
        "start_date",
        "end_date",
        "senate",
        "house",
        "total"
      ]
    },
    "disposition_of_executive_nominations": {
      "type": "object",
      "properties": {
        "start_date": {
          "type": "string"
        },
        "end_date": {
          "type": "string"
        },
        "civilian_nominees": {
          "type": "object",
          "properties": {
            "total": {
              "type": "integer"
            },
            "disposition": {
              "type": "object",
              "properties": {
                "confirmed": {
                  "type": "integer"
                },
                "unconfirmed": {
                  "type": "integer"
                },
                "withdrawn": {
                  "type": "integer"
                }
              },
              "required": [
                "confirmed",
                "unconfirmed",
                "withdrawn"
              ]
            }
          },
          "required": [
            "total",
            "disposition"
          ]
        },
        "other_civilian_nominees": {
          "type": "object",
          "properties": {
            "total": {
              "type": "integer"
            },
            "disposition": {
              "type": "object",
              "properties": {
                "confirmed": {
                  "type": "integer"
                },
                "unconfirmed": {
                  "type": "integer"
                }
              },
              "required": [
                "confirmed",
                "unconfirmed"
              ]
            }
          },
          "required": [
            "total",
            "disposition"
          ]
        },
        "air_force_nominees": {
          "type": "object",
          "properties": {
            "total": {
              "type": "integer"
            },
            "disposition": {
              "type": "object",
              "properties": {
                "confirmed": {
                  "type": "integer"
                },
                "unconfirmed": {
                  "type": "integer"
                }
              },
              "required": [
                "confirmed",
                "unconfirmed"
              ]
            }
          },
          "required": [
            "total",
            "disposition"
          ]
        },
        "army_nominees": {
          "type": "object",
          "properties": {
            "total": {
              "type": "integer"
            },
            "disposition": {
              "type": "object",
              "properties": {
                "confirmed": {
                  "type": "integer"
                },
                "unconfirmed": {
                  "type": "integer"
                },
                "withdrawn": {
                  "type": "integer"
                }
              },
              "required": [
                "confirmed",
                "unconfirmed",
                "withdrawn"
              ]
            }
          },
          "required": [
            "total",
            "disposition"
          ]
        },
        "navy_nominees": {
          "type": "object",
          "properties": {
            "total": {
              "type": "integer"
            },
            "disposition": {
              "type": "object",
              "properties": {
                "confirmed": {
                  "type": "integer"
                },
                "unconfirmed": {
                  "type": "integer"
                },
                "withdrawn": {
                  "type": "integer",
                  "optional": true
                }
              },
              "required": [
                "confirmed",
                "unconfirmed",
                "withdrawn"
              ]
            }
          },
          "required": [
            "total",
            "disposition"
          ]
        },
        "marine_corps_nominees": {
          "type": "object",
          "properties": {
            "total": {
              "type": "integer"
            },
            "disposition": {
              "type": "object",
              "properties": {
                "confirmed": {
                  "type": "integer"
                },
                "unconfirmed": {
                  "type": "integer"
                }
              },
              "required": [
                "confirmed",
                "unconfirmed"
              ]
            }
          },
          "required": [
            "total",
            "disposition"
          ]
        },
        "space_force_nominees": {
          "type": "object",
          "properties": {
            "total": {
              "type": "integer"
            },
            "disposition": {
              "type": "object",
              "properties": {
                "confirmed": {
                  "type": "integer"
                },
                "unconfirmed": {
                  "type": "integer"
                },
                "withdrawn": {
                  "type": "integer"
                }
              },
              "required": [
                "confirmed",
                "unconfirmed",
                "withdrawn"
              ]
            }
          },
          "required": [
            "total",
            "disposition"
          ]
        },
        "summary": {
          "type": "object",
          "properties": {
            "total_nominees_received_this_session": {
              "type": "integer"
            },
            "total_confirmed": {
              "type": "integer"
            },
            "total_unconfirmed": {
              "type": "integer"
            },
            "total_withdrawn": {
              "type": "integer"
            },
            "total_returned_to_white_house": {
              "type": "integer"
            }
          },
          "required": [
            "total_nominees_received_this_session",
            "total_confirmed",
            "total_unconfirmed",
            "total_withdrawn",
            "total_returned_to_white_house"
          ]
        }
      },
      "required": [
        "start_date",
        "end_date",
        "civilian_nominees",
        "army_nominees",
        "navy_nominees",
        "marine_corps_nominees",
        "space_force_nominees",
        "summary"
      ]
    },
    "footnote": {
      "type": "object",
      "properties": {
        "resume.legislative_activity.senate.measures_reported_total.total": {
          "type": "string"
        }
      },
      "required": [
        "resume.legislative_activity.senate.measures_reported_total.total"
      ]
    }
  },
  "required": [
    "url",
    "created_date",
    "congress",
    "session",
    "report_date",
    "legislative_activity",
    "disposition_of_executive_nominations",
    "footnote"
  ]
}

=== ahorjia/congress_resume/resumes/117_1.json
{
    "url": "https://www.senate.gov/reference/resources/pdf/Resumes/117_1.pdf",
    "created_date": "2023-02-01T08:00:00.000Z",
    "congress": 117,
    "session": 1,
    "report_date": "2022-04-28T05:00:00.000Z",
    "legislative_activity": {
        "start_date": "2021-01-03T05:00:00.000Z",
        "end_date": "2022-01-03T05:00:00.000Z",
        "senate": {
            "days_in_session": 192,
            "time_in_session": "PT1083H11M",
            "congressional_record": {
                "pages_of_proceedings": 9319
            },
            "public_bills_enacted_into_law": 38,
            "measures_passed_total": {
                "total": 423,
                "senate_bills": 94,
                "house_bills": 48,
                "senate_joint_resolutions": 5,
                "house_joint_resolutions": 1,
                "senate_concurrent_resolutions": 8,
                "house_concurrent_resolutions": 6,
                "simple_resolutions": 261
            },
            "measures_reported_total": {
                "total": 187,
                "senate_bills": 133,
                "house_bills": 14,
                "senate_joint_resolutions": 1,
                "simple_resolutions": 39
            },
            "special_reports": 8,
            "measures_pending_on_calendar": 149,
            "measures_introduced_total": {
                "total": 3969,
                "bills": 3429,
                "joint_resolutions": 33,
                "concurrent_resolutions": 24,
                "simple_resolutions": 483
            },
            "quorum_calls": 4,
            "yea_and_nay_votes": 528
        },
        "house": {
            "days_in_session": 166,
            "time_in_session": "PT708H7M",
            "congressional_record": {
                "pages_of_proceedings": 7849,
                "extensions_of_remarks": 1406
            },
            "public_bills_enacted_into_law": 47,
            "measures_passed_total": {
                "total": 506,
                "senate_bills": 30,
                "house_bills": 348,
                "senate_joint_resolutions": 4,
                "house_joint_resolutions": 2,
                "senate_concurrent_resolutions": 7,
                "house_concurrent_resolutions": 9,
                "simple_resolutions": 106
            },
            "measures_reported_total": {
                "total": 209,
                "house_bills": 166,
                "house_joint_resolutions": 1,
                "simple_resolutions": 42
            },
            "special_reports": 12,
            "measures_pending_on_calendar": 31,
            "measures_introduced_total": {
                "total": 7335,
                "bills": 6343,
                "joint_resolutions": 67,
                "concurrent_resolutions": 66,
                "simple_resolutions": 859
            },
            "quorum_calls": 1,
            "yea_and_nay_votes": 448
        },
        "total": {
            "measures_passed_total": {
                "total": 929
            },
            "measures_reported_total": {
                "total": 396
            },
            "measures_introduced_total": {
                "total": 11304
            }
        }
    },
    "disposition_of_executive_nominations": {
        "start_date": "2021-01-03T05:00:00.000Z",
        "end_date": "2022-01-03T05:00:00.000Z",
        "civilian_nominees": {
            "total": 716,
            "disposition": {
                "confirmed": 366,
                "unconfirmed": 303,
                "withdrawn": 47
            }
        },
        "other_civilian_nominees": {
            "total": 2763,
            "disposition": {
                "confirmed": 2471,
                "unconfirmed": 291
            }
        },
        "air_force_nominees": {
            "total": 6295,
            "disposition": {
                "confirmed": 6290,
                "unconfirmed": 5
            }
        },
        "army_nominees": {
            "total": 8607,
            "disposition": {
                "confirmed": 6614,
                "unconfirmed": 1992,
                "withdrawn": 1
            }
        },
        "navy_nominees": {
            "total": 4411,
            "disposition": {
                "confirmed": 4409,
                "unconfirmed": 1,
                "withdrawn": 1
            }
        },
        "marine_corps_nominees": {
            "total": 1644,
            "disposition": {
                "confirmed": 1323,
                "unconfirmed": 321
            }
        },
        "space_force_nominees": {
            "total": 1916,
            "disposition": {
                "confirmed": 1095,
                "unconfirmed": 2,
                "withdrawn": 819
            }
        },
        "summary": {
            "total_nominees_carried_over_from_first_session": 0,
            "total_nominees_received_this_session": 26351,
            "total_confirmed": 22568,
            "total_unconfirmed": 2915,
            "total_withdrawn": 868,
            "total_returned_to_white_house": 0
        }
    },
    "footnote": {
        "resume.legislative_activity.senate.measures_reported_total.total": "These figures include all measures reported, even if there was no accompanying report. A total of 53 written reports have been filed in the Senate, 221 reports have been filed in the House."
    }
}
